# Generated by Django 4.2 on 2023-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_g14', '0002_alter_organization_name_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('WA', 'WA'), ('NT', 'NT'), ('QSL', 'QSL')], max_length=10),
        ),
    ]
