# Generated by Django 4.2 on 2023-05-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_g14', '0008_remove_wasteitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
