# Generated by Django 4.2 on 2023-04-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group14_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Web_Introduction',
            new_name='Introduction',
        ),
    ]
