# Generated by Django 4.2 on 2023-04-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group14_app', '0002_rename_web_introduction_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Introduction',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
