# Generated by Django 4.2.1 on 2023-05-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group14_app', '0003_delete_introduction_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Your Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodDetail',
        ),
        migrations.DeleteModel(
            name='FoodWaste',
        ),
    ]
