# Generated by Django 4.2 on 2023-05-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group14_app', '0004_contact_delete_fooddetail_delete_foodwaste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=500)),
                ('foodname', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=100)),
                ('foodsize', models.CharField(max_length=10)),
                ('recorded', models.CharField(max_length=100)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group14_app.measurement')),
                ('wastetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group14_app.wastetype')),
            ],
        ),
    ]
