# Generated by Django 4.2.1 on 2023-05-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group14_app', '0003_delete_introduction_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodDetail',
        ),
        migrations.DeleteModel(
            name='FoodWaste',
        ),
    ]
