# Generated by Django 4.2 on 2023-05-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_g14', '0003_alter_organization_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_g14.organization'),
            preserve_default=False,
        ),
    ]
