# Generated by Django 4.2 on 2023-05-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_g14', '0005_alter_organization_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('waste_quantity', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_g14.user')),
                ('location', models.ManyToManyField(to='admin_g14.location')),
                ('organization', models.ManyToManyField(to='admin_g14.organization')),
                ('waste_item', models.ManyToManyField(to='admin_g14.wasteitem')),
            ],
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
    ]
