# Generated by Django 4.2 on 2023-05-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_g14', '0007_remove_wasteitem_location_alter_wastecat_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteitem',
            name='description',
        ),
    ]
